#!/usr/bin/python3
"""This script lists all the states from the database hbtn_0e_0_usa.
"""

import sys
import MySQLdb
from sqlalchemy import create_engine, MetaData
from sqlalchemy.orm import sessionmaker

if __name__ == "__main__":
    db = MySQLdb.connect(host="localhost", user=sys.argv[1], passwd=sys.argv[2],
                         db=sys.argv[3])
    engine = create_engine("mysql+mysqldb://{}:{}@localhost:3306/{}".format(
                           sys.argv[1], sys.argv[2], sys.argv[3]))
    metadata = MetaData(engine)
    Session = sessionmaker(bind=engine)
    session = Session()

    conn = engine.connect()


    states = metadata.tables["states"]
    select_obj = states.select()
    res_proxy = conn.execute(select_obj)
    
    for row in res_proxy.fetchall():
        print(row)
